engines:
    radon:
        enabled: true
        config:
            threshold: 'B'
    pep8:
        enabled: true
    duplication:
        enabled: true
        config:
        languages:
            python:
                python_version: 3
    sonar-python:
        enabled: true
        config:
            tests_patterns:
                - "tests/*"
            minimum_severity: minor
ratings:
    paths:
    - "**.py"
exclude_paths:
- "tests/*"
- "exercises/*"
